---

- name: adding 'grafana-agent' to group root
  user:
    name: 'grafana-agent'
    groups: root
    append: yes
  when:
    agent_addgrouproot | bool
  notify:
    - restart grafana-agent

- name: Configure grafana-agent
  ansible.builtin.template:
    src: grafana-agent.yaml.j2
    dest: /etc/grafana-agent.yaml
    owner: root
    group: grafana-agent
    mode: '0644'
  notify:
    - restart grafana-agent
