---
# tasks file for grafana-agent

- name: import assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

#- name: download foo.conf
#  get_url:
#    url: {{ agent_url }}
#    dest: /tmp/grafana-agent.deb
#    mode: 0644

- name: Install grafana-agent .deb package from the internet
  apt:
    deb: "{{ agent_url }}"

- name: Configure grafana-agent
  ansible.builtin.template:
    src: grafana-agent.yaml.j2
    dest: /etc/rafana-agent.yaml
    owner: root
    group: grafana-agent
    mode: '0644'
