---
# tasks file for grafana-agent

- name: import assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Install grafana-agent .deb package from the internet
  apt:
    deb: "{{ agent_url }}.deb"
  when:
    - ansible_os_family == "Debian"

- name: Install grafana-agent .rpm package from the internet
  yum:
    name: "{{ agent_url }}.rpm"
    disable_gpg_check: yes
  when:
    - ansible_os_family == "RedHat"

- name: Configure grafana-agent
  ansible.builtin.template:
    src: grafana-agent.yaml.j2
    dest: /etc/grafana-agent.yaml
    owner: root
    group: grafana-agent
    mode: '0644'
  notify:
    - restart grafana-agent
