---
# tasks file for grafana-agent

- name: import assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: download foo.conf
  get_url:
    url: {{ agent_url }}
    dest: /tmp/grafana-agent.deb
    mode: 0644
